version: '3.8'
volumes:
  volumendatabase:
services:
  # app:
  #   build: .
  # depends_on:
  #   - db
  db:
    image: mongo:latest
    restart: always
    ports:
      - 27099:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: multi
      MONGO_INITDB_ROOT_PASSWORD: brain
      MONGO_INITDB_DATABASE: multibraindatabase
    volumes:
      - volumendatabase:/data/db
  