version: '3.8'
services:
  db:
    image: mongo:latest
    restart: always
    ports:
      - 27099:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: multi
      MONGO_INITDB_ROOT_PASSWORD: brain
